#!/bin/sh
#________________________________________
#
#

#________________________________________
# Declare global variables
#

#

chef_client_name='default'
chef_server_host='localhost'
chef_server_port=8889
knife_config_path="`pwd`/.chef/knife.rb"
replace_knife_config='false'

#

chef_client_key_path="`pwd`/.chef/${chef_client_name}.pem"


#________________________________________
# Begin application execution
#

# Create directories

for dir in .chef cookbooks data_bags environments nodes roles; do
  mkdir -p $dir
done

# Generate a knife configuration file

test "$replace_knife_config" != "false" && cat > $knife_config_path <<EOF
#
chef_base_dir    = Dir.getwd
client_name      = '$chef_client_name'
#
chef_config_dir  = "#{chef_base_dir}/.chef"
#
cache_path       "#{chef_config_dir}/cache"
chef_server_url  'http://${chef_server_host}:${chef_server_port}'
client_key       "#{chef_config_dir}/#{client_name}.pem"
cookbook_path    "#{chef_base_dir}/cookbooks"
node_name        client_name
ssl_verify_mode  :verify_none
#
EOF

# Generate the client's private key

openssl genrsa 2048 > $chef_client_key_path
chmod 600 $chef_client_key_path

#
